name: Build
description: Builds the plugin and packages it
inputs:
  version:
    description: Version string to use
    required: true
outputs:
  plugin-artifact:
    description: Path to built ts3_plugin file
  debugsymbols-artifact:
    description: Path to generated debugging symbols file
runs:
  using: 'docker'
  image: Dockerfile
  args:
    - ${{ inputs.version }}
