name: Build the plugin on push or PR

on:
  push:
    paths-ignore:
    - 'docker/**'
    - '.github/workflows/docker-images-workflow.yml'
  pull_request:
    paths-ignore:
    - 'docker/**'
    - '.github/workflows/docker-images-workflow.yml'

jobs:
  build:
    strategy:
      matrix:
        config:
          # - os: ubuntu
          #   runner: ubuntu-latest
          - os: windows
            runner: windows-2016
            image: docker.pkg.github.com/${{ github.repository }}/windows:latest

    runs-on: ${{ matrix.config.runner }}

    steps:
    # Checkout sources and get plugin version string from latest tag
    - uses: actions/checkout@v2

    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Get previous git tag
      id: previoustag
      uses: ./.github/actions/github-action-get-previous-tag # WyriHaximus/github-action-get-previous-tag@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Parse version string 
      id: version
      uses: frabert/replace-string-action@v1.1
      with:
        pattern: v([.0-9]+)
        string: ${{ steps.previoustag.outputs.tag }}
        replace-with: $1

    - name: Build plugin package
      id: package
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | \
          docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin
        docker pull ${{ matrix.config.image }} || true
        docker run \
          --rm \
          --volume ${PWD}:/build \
          ${{ matrix.config.image }} \
          ${{ steps.version.outputs.replaced }}

    # Upload plugin files for releasing
    - name: Upload plugin installer artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.config.os }}-plugin
        path: ${{ steps.package.outputs.plugin-artifact }}

    - name: Upload debugging symbols
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.config.os }}-dbgsymbols
        path: ${{ steps.package.outputs.debugsymbols-artifact }}
