name: Build Docker image (Windows)

on:
  push:
    paths:
    - 'docker/windows/**'
    - '.github/workflows/docker-windows-workflow.yml'

env:
  IMAGE_NAME: jhakonen/tessumod:plugin-windows-latest
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: Build Docker image with Visual C++ 2015 build tools and Qt Framework
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      shell: bash
      run: |
        echo "Login to Docker Hub"
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

        echo "Build and push the final stage"
        docker build -t $IMAGE_NAME docker/windows
        docker history $IMAGE_NAME
        docker push $IMAGE_NAME
